Feat/add service catalog support
SquadcastHub/terraform-provider-squadcast pull request #26
Opened 2022-11-15 18:33 UTC by mohammadmuazam

2022-11-18 02:24 UTC, roshan8 commented on internal/provider/data_source_service.go
> +				Computed:    true,
isn't it optional?

2022-11-18 06:03 UTC, dheeraj-squadcast requested changes

2022-11-18 06:03 UTC, dheeraj-squadcast commented on docs/data-sources/service.md
> +- `type` (String)
What should this be? please specify in the docs.

2022-11-18 06:03 UTC, dheeraj-squadcast commented on docs/resources/service.md
> +    type = "user"
Try to remove this parameter if it can only be "user". `maintainer_id` perhaps

2022-11-18 06:03 UTC, dheeraj-squadcast commented on docs/resources/service.md
> +- `type` (String) The type of the maintainer. (user or team)
Consider removing this

2022-11-18 06:03 UTC, dheeraj-squadcast commented on examples/resources/squadcast_service/resource.tf
>  data "squadcast_team" "example_team_resource" {
please remove all `_resource` prefixes in `examples/`

2022-11-18 06:03 UTC, dheeraj-squadcast commented on internal/api/services.go
> +
Remove extra empty line. Also, please add this to .vscode/settings.json

```
{
  "editor.autoIndent": "brackets",
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "files.insertFinalNewline": true,
  "files.trimTrailingWhitespace": true,
  "files.trimFinalNewlines": true
}
```

2022-11-18 06:03 UTC, dheeraj-squadcast commented on internal/provider/data_source_service.go
> +				Description: "service owner",
Capitalization

2022-11-18 06:03 UTC, dheeraj-squadcast commented on internal/provider/resource_service.go
> +				Description: "service owner",
Capitalization

2022-11-18 06:03 UTC, dheeraj-squadcast commented on internal/provider/resource_service.go
> +				Description: "service tags",
Capitalization

2022-11-18 06:03 UTC, dheeraj-squadcast commented on internal/provider/resource_service.go
> +				Description: "List of alert source names (shortNames).",
Please remove `(shortNames)`, it doesn't make sense to someone reading the docs.

2022-11-18 07:48 UTC, dheeraj-squadcast approved these changes

2022-11-22 03:38 UTC, roshan8 approved these changes

2022-11-22 03:38 UTC, roshan8 commented on internal/provider/resource_service.go
> +	_, err := client.UpdateService(ctx, d.Id(), &updateReq)
Same code seems to be replicated twice, can we move this to a func?

2022-11-22 05:11 UTC, Lucifer8729 commented on internal/provider/resource_service.go
> +	_, err := client.UpdateService(ctx, d.Id(), &updateReq)
we can, but inside this whole block there are only like 4-5 lines of code repeated, half of it are assignment statements, not sure making it a func will be necessary

2022-11-22 05:16 UTC, merged