feat: entity ownership
SquadcastHub/terraform-provider-squadcast pull request #44
Opened 2023-05-22 05:24 UTC by Dineshsq

2023-05-23 05:43 UTC, roshan8 requested changes

2023-05-23 05:43 UTC, roshan8 commented on internal/provider/data_source_escalation_policy.go
> +				Elem: &schema.Resource{
lets add max item field

2023-05-23 15:01 UTC, mohammadmuazam commented on internal/provider/data_source_escalation_policy.go
> +				Elem: &schema.Resource{
This is a computed field inside data source, maxItems not needed here

2023-05-29 05:21 UTC, roshan8 commented
@mohammadmuazam Can you update the service_test as well?

2023-06-02 05:30 UTC, roshan8 approved these changes

2023-06-02 05:30 UTC, merged