fix: update entity_owner for all resources
SquadcastHub/terraform-provider-squadcast pull request #80
Opened 2024-03-14 15:55 UTC by mohammadmuazam

2024-03-19 10:43 UTC, Dineshsq approved these changes

2024-03-21 11:23 UTC, roshan8 requested changes

2024-03-21 11:23 UTC, roshan8 commented on docs/resources/escalation_policy.md
> +- `type` (String) Escalation policy owner type. (user or squad)
Supported values are "user" or "squad"

2024-03-21 11:23 UTC, roshan8 commented on docs/resources/schedule_v2.md
> -- `type` (String) Schedule owner type (user, team, squad).
Use description like "supported values are "user", "team" and "squad"
This applies to all the files

2024-04-01 06:52 UTC, roshan8 approved these changes

2024-04-01 06:52 UTC, merged